version: '3'
services:
    planner_app:
        image: gshau/astroimaging-planner:latest  # uncomment this line to pull down latest docker image 
        restart: always
        entrypoint: ["python", "./src/app.py"]
        ports:
            - "8050:8050"
        volumes:
            - ./conf:/app/conf
            - ${DATA_PATH}:/data:ro
        environment:
            POSTGRES_USER: astro_user
            POSTGRES_PASSWORD: andromeda
            POSTGRES_DB: fits_files
            PGPORT: 5432
            PGHOST: db
        depends_on:
            - db
            - watchdog
    watchdog:
        image: gshau/astroimaging-planner:latest  # uncomment this line to pull down latest docker image 
        restart: always
        entrypoint: ["python", "./src/watchdog.py"]
        volumes:
            - ./conf:/app/conf
            - ${DATA_PATH}:/data:ro
            - ${TARGETS_PATH}:/targets:ro
        environment:
            POSTGRES_USER: astro_user
            POSTGRES_PASSWORD: andromeda
            POSTGRES_DB: fits_files
            PGPORT: 5432
            PGHOST: db
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: astro_user
            POSTGRES_PASSWORD: andromeda
            POSTGRES_DB: fits_files
            PGPORT: 5432
        logging:
            options:
                max-size: 10m
                max-file: "3"                