version: '3'
services:
    app:
        build: .  # uncomment this line to build locally from source
        # image: gshau/astroimaging-planner:latest  # uncomment this line to pull down latest docker image 
        restart: always
        ports:
            - 8050:8050
        volumes:
            - /Volumes/Users/gshau/Dropbox/AstroPlanner/dash_app:/app
            # path to the config files - tailor this path to your circumstances
            - /Volumes/Users/gshau/Dropbox/AstroPlanner/dash_app/conf:/app/conf
            # your DATA_DIR, everything after this path is of the format {target_name}/*/{fits_file} - tailor this path to your circumstances
            - /Volumes/Users/gshau/Dropbox/AstroBox/data:/data:ro
            # your roboclip path - tailor this path to your circumstances, typically set as `C:\Users\UserName\Documents\Voyager\Data` in Windows
            - /Volumes/Users/gshau/Dropbox/AstroBox/roboclip:/roboclip:ro
        # networks: 
        #     - astroimaging_network
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        ports:
            - 5431:5431
        environment:
            POSTGRES_USER: astro_user
            POSTGRES_PASSWORD: andromeda
            POSTGRES_DB: fits_files
            PGPORT: 5431
        logging:
            options:
                max-size: 10m
                max-file: "3"                
    
    
# version: '3'
# services:
#     app:
#         build: .  # uncomment this line to build locally from source
#         # image: gshau/astroimaging-planner:latest  # uncomment this line to pull down latest docker image 
#         ports:
#             - 8050:8050
#         volumes:
#             - /Volumes/Users/gshau/Dropbox/AstroPlanner/dash_app:/app
#             # path to the config files - tailor this path to your circumstances
#             - /Volumes/Users/gshau/astroplanner/Voyager/conf:/app/conf
#             # your DATA_DIR, everything after this path is of the format {target_name}/*/{fits_file} - tailor this path to your circumstances
#             - /Volumes/Users/gshau/astroplanner/Voyager/fits_data:/data:ro
#             # your roboclip path - tailor this path to your circumstances, typically set as `C:\Users\UserName\Documents\Voyager\Data` in Windows
#             - /Volumes/Users/gshau/astroplanner/Voyager/Data:/roboclip:ro
