version: '3'
services:
    app:
        build: .
        ports:
            - 8050:8050
        environment:
            - DATA_DIR=/data
            - ROBOCLIP_FILE=/roboclip/VoyRC.mdb
        volumes:
            - /Volumes/Users/gshau/Dropbox/AstroBox/data:/data
            - /Volumes/Users/gshau/Dropbox/AstroBox/roboclip:/roboclip
            # - DEFAULT_PROFILE_PATH="/Volumes/Users/gshau/Dropbox/AstroBox/Voyager Profiles"

    # volumes:
    #   - .:/code
    # environment:
    #   FLASK_ENV: development
    # redis:
    #     image: "redis:alpine"
    # nginx: 
    #     image: nginx:latest
    #     container_name: nginx
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/nginx.conf
    #     ports:
    #         - 8088:8050
    #         - 443:443    
