version: '3'
services:
    planner_app:
        image: gshau/astroimaging-planner:latest
        restart: always
        container_name: planner
        entrypoint: ["python", "./src/app.py"]
        ports:
            - "8050:8050"
        volumes:
            - ./conf:/app/conf
            - ${DATA_PATH}:/data:ro
            - ./logs:/logs
        environment:
            POSTGRES_USER: astro_user
            POSTGRES_PASSWORD: andromeda
            POSTGRES_DB: fits_files
            PGPORT: 5432
            PGHOST: db
        depends_on:
            - db
            - watchdog
    watchdog:
        image: gshau/astroimaging-planner:latest
        restart: always
        container_name: watchdog
        entrypoint: ["python", "./src/watchdog.py"]
        volumes:
            - ./conf:/app/conf
            - ${DATA_PATH}:/data:ro
            - ${TARGETS_PATH}:/targets:ro
            - ./logs:/logs
        environment:
            POSTGRES_USER: astro_user
            POSTGRES_PASSWORD: andromeda
            POSTGRES_DB: fits_files
            PGPORT: 5432
            PGHOST: db
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        container_name: db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: astro_user
            POSTGRES_PASSWORD: andromeda
            POSTGRES_DB: fits_files
            PGPORT: 5432
        logging:
            options:
                max-size: 10m
                max-file: "3"                
    mqtt:
        image: eclipse-mosquitto
        container_name: mqtt
        expose:
            - 1883
        ports:
            - 1883:1883
        restart: unless-stopped                                