version: '3'
services:
    app:
        build: .
        ports:
            - 8050:8050
        volumes:
            - /Volumes/Users/gshau/Dropbox/AstroBox/data:/data:ro
            - /Volumes/Users/gshau/Dropbox/AstroBox/roboclip:/roboclip:ro
