
# DATA_DIR
# data_dir: ''


# FITs file patters in regex format, relative to DATA_DIR
fits_file_patterns:
  - "/*/*/*.[fF][iI][tT]"
  - "/*/*/*.[fF][iI][tT]s"
  - "/*/*/Lights/*.[fF][iI][tT]"
  - "/*/*/Lights/*.[fF][iI][tT][s]"

# target progress display mode - stack or group
progress_mode: 'group'

# Last number of days to show target progress, regardless of filters
progress_days_ago: 0