# FITs file patters in regex format, relative to DATA_DIR
fits_file_patterns:
  - "*/*/*.[fF][iI][tT]"
  - "*/*/*.[fF][iI][tT]s"
  - "*/*/*/*.[fF][iI][tT]"
  - "*/*/*/*.[fF][iI][tT]s"
  - "*.[fF][iI][tT]"
  - "*.[fF][iI][tT][s]"


# Default target status when initially parsing data
default_target_status: ''

# Inactive profiles to hide from the UI
inactive_profiles:
  - borg55fl asi2600mc
  - rasa8 asi2600mc

# target progress display mode - stack or group
progress_mode: 'group'

# Last number of days to show target progress, regardless of filters
progress_days_ago: 0

horizon_data:
  flat_horizon_alt: 10
  horizon_file: "data/custom_horizon.txt"
  alt_az_seperator: " "
  header_length: 3

# Webserver settings
localhost_only: "False"
debug: "True"

# Default location settings
lat: 43.37
lon: -88.37
utc_offset: -6
mpsas: 20.1
bandwidth: 120
k_extinction: 0.2
time_resolution: 300

# Specify fits header entries
fits_header_map:
  exposure: 
    - EXPTIME
    - EXPOSURE
  target_name: 
    - TARGET
  instrument: 
    - INSTRUME
  focal_length: 
    - FOCALLEN
  binning: 
    - XBINNING
  pixel_size:
    - XPIXSIZ

sensor_map:
  'null': null
  "QSI 690ws HW 12.01.00 FW 06.03.04": "QSI690-wsg8"
  "QHYCCD-Cameras-Capture": "QHY16200A"
  "AltaF-8300D2": "Alta_Camera_8300"

