# FITs file patters in regex format, relative to DATA_DIR
fits_file_patterns:
  - "/*/*/*.[fF][iI][tT]"
  - "/*/*/*.[fF][iI][tT]s"
  - "/*/*/Lights/*.[fF][iI][tT]"
  - "/*/*/Lights/*.[fF][iI][tT][s]"

# Default target status when initially parsing data
default_target_status: 'active'

# Inactive profiles to hide from the UI
inactive_profiles:
  - ap130 asi6200mm

# target progress display mode - stack or group
progress_mode: 'group'

# Last number of days to show target progress, regardless of filters
progress_days_ago: 0

horizon_data:
  flat_horizon_alt: 10
  horizon_file: "data/custom_horizon.txt"
  alt_az_seperator: " "
  header_length: 3

# Webserver settings
localhost_only: "False"
debug: "True"